services:
  minio:
    image: "minio/minio:RELEASE.2025-04-22T22-12-26Z"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "--console-address", ":9001", "/data"]
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  bucket_data:
    image: "minio/mc:RELEASE.2025-05-21T01-59-54Z"
    depends_on:
      minio:
          condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 user password123;
      /usr/bin/mc mb myminio/raw-data;
      /usr/bin/mc mb myminio/final-data;
      echo 'Бакеты созданы';
      exit 0;
      "
  etl_app:
    build: .
    volumes: 
      - ./data:/app/data
    depends_on:
      minio:
          condition: service_healthy
    environment:
      - S3_ENDPOINT=http://minio:9000
